# Generated by Django 5.1.7 on 2025-03-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiproblems', '0004_group_admin_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oiproblems.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
