# Generated by Django 5.1.7 on 2025-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiproblems', '0005_announcement_publisher_group_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='logo',
            new_name='large_logo',
        ),
        migrations.AddField(
            model_name='group',
            name='small_logo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
