# Generated by Django 5.1.7 on 2025-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiproblems', '0006_rename_logo_group_large_logo_group_small_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(max_length=1),
        ),
    ]
