# Generated by Django 5.1.7 on 2025-03-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiproblems', '0007_alter_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='large_logo',
        ),
        migrations.RemoveField(
            model_name='group',
            name='small_logo',
        ),
        migrations.AddField(
            model_name='group',
            name='logo_id',
            field=models.IntegerField(null=True),
        ),
    ]
